name: laravel-helth-check
services:
    php:
        container_name: php
        build:
            context: .
            dockerfile: ./Docker/Dockerfile
            target: php
        working_dir: /var/www/html
        volumes:
            - type: bind
              source: .
              target: /var/www/html
        depends_on:
            mysql:
              condition: service_healthy
    mysql:
        container_name: mysql
        image: mysql:8.0.42-debian
        ports:
            - "3307:3306"
        environment:
            MYSQL_HOST: "mysql"
            MYSQL_DATABASE: "health"
            MYSQL_USER: "hosein"
            MYSQL_PASSWORD: "hosein1992"
            MYSQL_ROOT_PASSWORD: "supersecret"
        volumes:
            - type: volume
              source: mysql
              target: /var/lib/mysql
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h mysql -u hosein -phosein1992 || exit 1"]
            interval: 5s
            timeout: 5s
            retries: 10


volumes:
    mysql:
