name: laravel-helth-check
services:
    php:
        container_name: php
        build:
            context: .
            dockerfile: ./Docker/Dockerfile
            target: php
        working_dir: /var/www/html
        volumes:
            - type: bind
              source: .
              target: /var/www/html
        depends_on:
            mysql:
              condition: service_healthy
    nginx:

        container_name: nginx
        build:
            context: .
            dockerfile: ./Docker/Dockerfile
            target: nginx
        volumes:
          - type: bind
            source: ./public
            target: /var/www/html/public
        develop:
            watch:
                - action: rebuild
                  path: ./Docker/nginx.conf
                  target: /etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        depends_on:
            - php
            - node
    node:
        container_name: node
        build:
            context: .
            dockerfile: ./Docker/Dockerfile
            target: node
        volumes:
            - type: bind
              source: ./resources
              target: /var/www/html/resources
        develop:
            watch:
                - action: rebuild
                  path: ./package.json
                  target: /var/www/html/package.json
                - action: rebuild
                  path: ./package-lock.json
                  target: /var/www/html/package-lock.json
                - action: rebuild
                  path: ./vite.config.js
                  target: /var/www/html/vite.config.js
                - action: rebuild
                  path: ./node_modules
                  target: /var/www/html/node_modules
    mysql:
        container_name: mysql
        image: mysql:8.0.42-debian
        ports:
            - "3307:3306"
        environment:
            MYSQL_HOST: "mysql"
            MYSQL_DATABASE: "health"
            MYSQL_USER: "hosein"
            MYSQL_PASSWORD: "hosein1992"
            MYSQL_ROOT_PASSWORD: "supersecret"
        volumes:
            - type: volume
              source: mysql
              target: /var/lib/mysql
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h mysql -u hosein -phosein1992 || exit 1"]
            interval: 5s
            timeout: 5s
            retries: 10


volumes:
    mysql:
